version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk  
    steps:
      - checkout  

      
      - run:
          name: Kompilacja kodu Java
          command: |
            mkdir -p build  
            javac -d build src/main/java/**/*.java  
      # Krok 2: Kompilacja test贸w
      - run:
          name: Kompilacja test贸w Java
          command: |
            javac -d build -cp build src/test/java/**/*.java  

      # Krok 3: Uruchomienie test贸w jednostkowych
      - run:
          name: Uruchamianie test贸w JUnit
          command: |
            java -cp "build:libs/*" org.junit.platform.console.ConsoleLauncher --scan-classpath  

      # Krok 4: Tworzenie pliku JAR
      - run:
          name: Tworzenie pliku JAR
          command: |
            jar cvf build/kalkulator.jar -C build .  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  
